### ISSUE TITLE
storing the password in db

### ISSUE THREAD

**Issue by doron123** [mohiva/play-silhouette-angular-seed#42]
i wanna store the password to db, so add a line of code in the file '/app/modules/SilhouetteModule', as below:

![qq 20160424192119](https://cloud.githubusercontent.com/assets/8838800/14767156/92b5b74e-0a51-11e6-8663-7c080cc98307.png)

but it has an error.

### Library Dependencies
```
libraryDependencies ++= Seq(
  "com.mohiva" %% "play-silhouette" % "4.0.0-BETA4",
  "com.mohiva" %% "play-silhouette-persistence-memory" % "4.0.0-BETA4",
  "com.mohiva" %% "play-silhouette-password-bcrypt" % "4.0.0-BETA4",
  "net.codingwell" %% "scala-guice" % "4.0.1",
  "com.iheart" %% "ficus" % "1.2.3",
  "com.mohiva" %% "play-silhouette-testkit" % "4.0.0-BETA4" % "test",
  "com.typesafe.play" %% "play-slick" % "2.0.0",
  "com.typesafe.play" %% "play-slick-evolutions" % "2.0.0",
  "org.postgresql" % "postgresql" % "9.4-1201-jdbc41",
  "org.slf4j" % "slf4j-nop" % "1.6.4",
  evolutions,
  cache,
  filters
)
```
### Expected Behavior

expect call the PasswordInfoDAO to store the password in db

![qq 20160424192552](https://cloud.githubusercontent.com/assets/8838800/14767182/35b975fc-0a52-11e6-9687-cc033dc67d12.png)

### Actual Behavior

![qq 20160424192955](https://cloud.githubusercontent.com/assets/8838800/14767204/c38d1b5e-0a52-11e6-8306-3d13f33177f3.png)

**Comment by akkie** [comment]
The error messages says that the `DelagableAuthInfoDAO` is already bound!

The `play-silhouette-persistence-memory` module provides a [reference.conf](https://github.com/mohiva/play-silhouette/blob/master/silhouette-persistence-memory/src/main/resources/reference.conf) which binds the [PersistenceModule](https://github.com/mohiva/play-silhouette/blob/master/silhouette-persistence-memory/src/main/scala/com/mohiva/play/silhouette/persistence/memory/modules/PersistenceModule.scala) automatically. I think I will remove this automatic binding, because you are the second which has problems with it. It should also solve [this issue](https://github.com/mohiva/play-silhouette/pull/466#issuecomment-211758965).

**Comment by doron123** [comment]
i user com.mohiva.play.silhouette.persistence.memory.daos.PasswordInfoDAO instead of DelegableAuthInfoDAO, it work!

**Comment by akkie** [comment]
Currently you must not bind anything! As an alternative, you should add the following line to your application.conf:
```scala
play.modules.disabled += "com.mohiva.play.silhouette.persistence.memory.modules.PersistenceModule"
```

Then you can configure the bindings by yourself.

**Comment by doron123** [comment]
OK, thank you very much for your help
